# Site settings
name: Jeevanshi Sharma
title: Jeevanshi Sharma | Machine Learning Explorer
description: Passionate for solving real world problems using Machine Learning.
url: https://github.com/Femme-js
baseurl: ''
email: sharma.jivanshi@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:sharma.jivanshi@gmail.com
  - title: twitter
    url: https://twitter.com/_Jeevanshi_
  - title: instagram
    url: https://instagram.com/tech_and_us
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/Femme-js
  - title: linkedin
    url: https://www.linkedin.com/in/femme-js/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
